import Image from 'next/image';
import React from 'react';
import { getDogs } from '../../database/dogs';

export const metadata = {
  title: 'Dogs page',
  description: 'Generated by create next app',
};
export default async function DogsPage() {
  const dogs = await getDogs();
  if (!dogs) {
    return {
      notFound: true,
    };
  }
  return (
    <main>
      <h1>These are my dogs</h1>
      {dogs.map((dog) => (
        <li key={`dog-${dog.id}`}>
          <a data-test-id={`dog-${dog.id}`} href={`/dogs/${dog.id}`}>
            {dog.id} {dog.name}
            <Image src={dog.image} width={200} height={200} alt={dog.name} />
          </a>
        </li>
      ))}
    </main>
  );
}
